# Generated by Django 5.0.6 on 2024-05-30 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobofferanalyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('comment', models.CharField(max_length=500)),
                ('note', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobofferanalyzer.factor')),
                ('job_offer_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobofferanalyzer.jobofferanalysis')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='related_users',
            field=models.ManyToManyField(through='jobofferanalyzer.Scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
