# Generated by Django 5.0.6 on 2024-05-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobofferanalyzer', '0002_jobofferanalysis_scores_factor_related_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
