# Generated by Django 5.0.6 on 2024-05-30 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobofferanalyzer', '0003_scores_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='related_users',
            field=models.ManyToManyField(related_name='factors', through='jobofferanalyzer.Scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
