# Generated by Django 5.0.6 on 2024-06-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobofferanalyzer', '0005_jobofferanalysis_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobofferanalysis',
            old_name='user',
            new_name='user_id',
        ),
    ]
