# Generated by Django 5.0.6 on 2024-06-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobofferanalyzer', '0006_rename_user_jobofferanalysis_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobofferanalysis',
            old_name='user_id',
            new_name='user',
        ),
    ]
