# Generated by Django 5.0.6 on 2024-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobofferanalyzer', '0007_rename_user_id_jobofferanalysis_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferanalysis',
            name='comment',
            field=models.CharField(max_length=3000),
        ),
    ]
